version: '3'
services:
  api:
    image: "java_api"
    networks: 
      - backend 
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: "frontend_angular"
    networks:
      - backend
    ports:
      - "80:80"
    depends_on:
      - api  
    deploy:
      restart_policy:
        condition: on-failure

networks:
  backend: